name: core
description: Core package.
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Network & API
  dio: 5.7.0
  retrofit: 4.4.1
  json_annotation: 4.9.0

  #State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #Data & Persistence
  shared_preferences: ^2.3.3

  # internalization
  easy_localization: ^3.0.7

  #Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  #Navigation & Routing
  go_router: ^14.6.0

  #Utilities
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.4
  logger: ^2.5.0

  #Permissions
  permission_handler: ^11.3.1

  #UI
  flutter_adaptive_scaffold: ^0.3.1

  #Notifications
  flutter_local_notifications: ^18.0.1

  #Firebase
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5

  # packages
  components_library:
    path: ../components_library

dev_dependencies:
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
