name: feature_projects
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

dev_dependencies:

  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
