name: components_library
description: Package contains library of base view components.
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shimmer: 3.0.0
  fluentui_system_icons: 1.1.264
  lottie: 3.1.3
  easy_localization: 3.0.7
  flutter_svg: 2.0.14
  google_fonts: 6.2.1
